import {
  User,
  WasteCategory,
  ClassificationResult,
  CollectionPoint,
  CollectionRecord,
  IncidentReport,
  DatasetSample,
  SystemLog,
  EducationalArticle,
} from '../types';

export const INITIAL_USERS: User[] = [
  {
    id: 'u-1',
    name: 'Andrés Gómez',
    email: 'andres.gomez@ciudadano.org',
    role: 'ciudadano',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?w=150',
    neighborhood: 'El Poblado',
    city: 'Medellín',
    createdAt: '2026-01-15',
    points: 480,
    badge: 'Reciclador de Oro',
  },
  {
    id: 'u-2',
    name: 'Javier Restrepo',
    email: 'javier.restrepo@asociacion.org',
    role: 'reciclador',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150',
    neighborhood: 'La Laureles',
    city: 'Medellín',
    createdAt: '2025-11-20',
    points: 1250,
    badge: 'Héroe Ambiental',
  },
  {
    id: 'u-3',
    name: 'Dra. Elena Monsalve',
    email: 'elena.monsalve@ecovision.ai',
    role: 'administrador',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150',
    neighborhood: 'Centro',
    city: 'Bogotá',
    createdAt: '2025-08-10',
    points: 0,
    badge: 'Docente Investigador',
  },
  {
    id: 'u-4',
    name: 'Ing. Mateo Bermúdez',
    email: 'admin@ecovision.ai',
    role: 'super_admin',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150',
    neighborhood: 'Chicó',
    city: 'Bogotá',
    createdAt: '2025-01-01',
    points: 0,
    badge: 'Arquitecto Principal',
  },
];

export const WASTE_CATEGORIES: Record<string, WasteCategory> = {
  papel: {
    id: 'papel',
    name: 'Papel y Archivo',
    colombianBag: {
      colorName: 'Blanco',
      hex: '#ffffff',
      bgClass: 'bg-slate-100 text-slate-800 border-slate-300',
      textClass: 'text-slate-800',
      borderClass: 'border-slate-300',
      description: 'Bolsa Blanca: Residuos aprovechables secos y limpios.',
    },
    description: 'Hojas de papel impresas, cuadernos, periódicos y revistas secos sin grasa ni parafina.',
    examples: ['Hojas de bond', 'Revistas', 'Periódicos', 'Sobres', 'Folletos'],
    recyclingInstructions: [
      'Verifica que el papel esté completamente seco y libre de aceite o comida.',
      'Asegúrate de retirar ganchos metalizados o espirales plásticos si es posible.',
      'Pliega o dobla las hojas ordenadamente para optimizar el espacio en la bolsa blanca.',
    ],
    co2SavedPerKg: 1.8,
    waterSavedLiters: 26.0,
    energySavedPerKg: 4.0,
  },
  carton: {
    id: 'carton',
    name: 'Cartón y Empaques',
    colombianBag: {
      colorName: 'Blanco',
      hex: '#ffffff',
      bgClass: 'bg-slate-100 text-slate-800 border-slate-300',
      textClass: 'text-slate-800',
      borderClass: 'border-slate-300',
      description: 'Bolsa Blanca: Residuos aprovechables secos.',
    },
    description: 'Cajas de cartón corrugado, cajas de cereales, tubos de papel higiénico y empaques plegadizos.',
    examples: ['Cajas de envío', 'Cartón ondulado', 'Empaques de cereal', 'Tubos de cartón'],
    recyclingInstructions: [
      'Desarma y aplana completamente la caja para reducir volumen.',
      'Retira la cinta adhesiva plástica pesada.',
      'Si el cartón está mojado o grasoso por comida (ej. caja de pizza), debe ir a la Bolsa Negra.',
    ],
    co2SavedPerKg: 2.1,
    waterSavedLiters: 30.0,
    energySavedPerKg: 4.5,
  },
  pet: {
    id: 'pet',
    name: 'Plástico PET y Rígidos',
    colombianBag: {
      colorName: 'Blanco',
      hex: '#ffffff',
      bgClass: 'bg-slate-100 text-slate-800 border-slate-300',
      textClass: 'text-slate-800',
      borderClass: 'border-slate-300',
      description: 'Bolsa Blanca: Envases plásticos limpios.',
    },
    description: 'Botellas de agua, gaseosas, envases de detergente, champú y contenedores de plástico limpio.',
    examples: ['Botella PET transparente', 'Envase de champú', 'Frasco de detergente', 'Tapa plástica'],
    recyclingInstructions: [
      'Vacía completamente los líquidos sobrantes.',
      'Enjuaga levemente con un poco de agua residual si tiene jarabes o lácteos.',
      'Comprime la botella quitándole el aire y vuelve a colocarle la tapa.',
    ],
    co2SavedPerKg: 1.5,
    waterSavedLiters: 18.0,
    energySavedPerKg: 5.2,
  },
  vidrio: {
    id: 'vidrio',
    name: 'Vidrio y Botellas',
    colombianBag: {
      colorName: 'Blanco',
      hex: '#ffffff',
      bgClass: 'bg-slate-100 text-slate-800 border-slate-300',
      textClass: 'text-slate-800',
      borderClass: 'border-slate-300',
      description: 'Bolsa Blanca: Vidrio entero y enjuagado.',
    },
    description: 'Botellas de bebidas, frascos de conserva, conservas de vidrio transparentes o de color.',
    examples: ['Botella de jugo o cerveza', 'Frasco de mermelada', 'Frasco de café'],
    recyclingInstructions: [
      'Lava internamente para eliminar residuos orgánicos.',
      'Remueve tapas metálicas o plásticas y colócalas en su categoría correspondiente.',
      'Si el vidrio está roto, envuélvelo en papel periódico o cartón y rotúlalo con la palabra "PELIGRO: VIDRIO ROTO".',
    ],
    co2SavedPerKg: 0.3,
    waterSavedLiters: 1.2,
    energySavedPerKg: 1.1,
  },
  metal: {
    id: 'metal',
    name: 'Metales y Latas',
    colombianBag: {
      colorName: 'Blanco',
      hex: '#ffffff',
      bgClass: 'bg-slate-100 text-slate-800 border-slate-300',
      textClass: 'text-slate-800',
      borderClass: 'border-slate-300',
      description: 'Bolsa Blanca: Latas de aluminio y hojalata.',
    },
    description: 'Latas de aluminio para bebidas, conservas de atún, tapas metálicas y utensilios de acero limpio.',
    examples: ['Lata de cerveza / soda', 'Lata de atún', 'Lata de maíz', 'Tapa metálica de frasco'],
    recyclingInstructions: [
      'Lava y retira exceso de grasa u alimentos.',
      'Empuja la tapa hacia el interior de la lata para evitar cortaduras a los recicladores.',
      'Compacta la lata de aluminio con el pie o la mano si es posible.',
    ],
    co2SavedPerKg: 9.0,
    waterSavedLiters: 40.0,
    energySavedPerKg: 14.0,
  },
  organico: {
    id: 'organico',
    name: 'Orgánicos Aprovechables',
    colombianBag: {
      colorName: 'Verde',
      hex: '#16a34a',
      bgClass: 'bg-emerald-600 text-white border-emerald-700',
      textClass: 'text-emerald-700',
      borderClass: 'border-emerald-600',
      description: 'Bolsa Verde: Residuos orgánicos biodegradables para compostaje.',
    },
    description: 'Cascara de frutas y verduras, restos de hortalizas, restos de podas de jardín, borra de café y cáscaras de huevo.',
    examples: ['Cáscaras de banano / papa / naranja', 'Restos de hortalizas', 'Cunchos de café', 'Restos de césped'],
    recyclingInstructions: [
      'Deposita directamente en la Bolsa Verde sin mezclar con plásticos ni metales.',
      'No incluyas carne cocinada ni grasas animales excesivas si se destina a compost doméstico rápido.',
      'Ideal para llevar a huertas comunitarias o puntos de compostaje local.',
    ],
    co2SavedPerKg: 0.8,
    waterSavedLiters: 5.0,
    energySavedPerKg: 0.2,
  },
  electronico: {
    id: 'electronico',
    name: 'Residuos Electrónicos (RAEE)',
    colombianBag: {
      colorName: 'Rojo',
      hex: '#dc2626',
      bgClass: 'bg-red-600 text-white border-red-700',
      textClass: 'text-red-600',
      borderClass: 'border-red-600',
      description: 'Manejo Especial / Punto Rojo EcoGuardia (Punto Azul / RAEE).',
    },
    description: 'Equipos electrónicos, cables, baterías, tarjetas madre, bombillos ahorradores y celulares en desuso.',
    examples: ['Celular antiguo', 'Cargador / Cable USB', 'Tarjeta de circuito', 'Batería AA / Litio'],
    recyclingInstructions: [
      'No desechar en la basura común ni en bolsas blanca o negra.',
      'Llévalo a contenedores de recolección selectiva RAEE en centros comerciales o supermercados.',
      'Asegúrate de borrar la información personal de dispositivos de almacenamiento.',
    ],
    co2SavedPerKg: 3.5,
    waterSavedLiters: 50.0,
    energySavedPerKg: 8.0,
  },
  peligroso: {
    id: 'peligroso',
    name: 'Residuos Peligrosos y Hospitalarios',
    colombianBag: {
      colorName: 'Rojo',
      hex: '#dc2626',
      bgClass: 'bg-red-600 text-white border-red-700',
      textClass: 'text-red-600',
      borderClass: 'border-red-600',
      description: 'Bolsa / Guardián Rojo: Manejo especial bioinfeccioso o químico.',
    },
    description: 'Medicamentos vencidos, jeringas, aceites usados de cocina, solventes, pintura y químicos domésticos.',
    examples: ['Medicamento vencido', 'Jeringa usada', 'Aceite vegetal usado en botella', 'Bote de pintura'],
    recyclingInstructions: [
      'Medicamentos vencidos: Entregar en puntos "Punto Azul".',
      'Aceite de cocina usado: Dejar enfriar, embotellar en plástico PET y llevar a punto limpio.',
      'Nunca arrojar aceite usado por el sifón ni mezclar químicos.',
    ],
    co2SavedPerKg: 1.2,
    waterSavedLiters: 1000.0, // Prevent water contamination
    energySavedPerKg: 0.5,
  },
  no_reciclable: {
    id: 'no_reciclable',
    name: 'No Aprovechables / Ordinarios',
    colombianBag: {
      colorName: 'Negro',
      hex: '#1e293b',
      bgClass: 'bg-slate-900 text-white border-slate-950',
      textClass: 'text-slate-900',
      borderClass: 'border-slate-800',
      description: 'Bolsa Negra: Residuos que deben ir al relleno sanitario.',
    },
    description: 'Servilletas usadas, papel higiénico, cartones contaminados con grasa/comida, colillas de cigarrillo, empaques metalizados de papas.',
    examples: ['Servilleta usadada', 'Papel higiénico', 'Caja de pizza impregnada de queso', 'Empaque de frituras aluminio-plástico'],
    recyclingInstructions: [
      'Depositar obligatoriamente en Bolsa Negra según la Res. 2184 de 2019 de Colombia.',
      'Asegurar el nudo de la bolsa para evitar fugas de olores.',
      'Entregar únicamente en los días indicados por el operador de aseo público.',
    ],
    co2SavedPerKg: 0.0,
    waterSavedLiters: 0.0,
    energySavedPerKg: 0.0,
  },
};

export const INITIAL_CLASSIFICATIONS: ClassificationResult[] = [
  {
    id: 'cls-101',
    userId: 'u-1',
    userName: 'Andrés Gómez',
    imageUrl: 'https://images.unsplash.com/photo-1530587191325-3db32d826c18?w=500',
    wasteType: 'pet',
    wasteName: 'Botella de Agua PET Transparente 500ml',
    confidence: 96.4,
    inferenceTimeMs: 142,
    bagColor: 'Blanco',
    colombianNormNote: 'Resoluciòn 2184/2019: Depositar en Bolsa Blanca limpia y compactada.',
    recyclingSteps: [
      'Desocupar todo el líquido residual.',
      'Aplastar la botella para optimizar volumen.',
      'Tapar nuevamente y arrojar en bolsa blanca.',
    ],
    environmentalTips: [
      'Una sola botella PET tarda más de 450 años en degradarse en un relleno sanitario.',
      'Reciclar esta botella ahorra la energía suficiente para encender un bombillo LED por 6 horas.',
    ],
    estimatedWeightKg: 0.08,
    co2AvoidedKg: 0.12,
    waterSavedLiters: 1.44,
    energySavedKwh: 0.41,
    createdAt: '2026-07-25 10:15',
    status: 'verificado',
  },
  {
    id: 'cls-102',
    userId: 'u-1',
    userName: 'Andrés Gómez',
    imageUrl: 'https://images.unsplash.com/photo-1589939705384-5185137a7f0f?w=500',
    wasteType: 'carton',
    wasteName: 'Caja de Envíos Corrugada Doble Pared',
    confidence: 94.1,
    inferenceTimeMs: 168,
    bagColor: 'Blanco',
    colombianNormNote: 'Resoluciòn 2184/2019: Depositar aplanada en Bolsa Blanca.',
    recyclingSteps: [
      'Remover la cinta adhesiva de embalaje.',
      'Desarmar la caja y doblar los extremos.',
      'Asegurar de mantener en un lugar seco hasta entregarlo al reciclador.',
    ],
    environmentalTips: [
      '1 tonelada de cartón reciclado evita la tala de 17 árboles adultos.',
    ],
    estimatedWeightKg: 0.45,
    co2AvoidedKg: 0.94,
    waterSavedLiters: 13.5,
    energySavedKwh: 2.02,
    createdAt: '2026-07-24 16:30',
    status: 'verificado',
  },
  {
    id: 'cls-103',
    userId: 'u-1',
    userName: 'Andrés Gómez',
    imageUrl: 'https://images.unsplash.com/photo-1550989460-0adf9ea622e2?w=500',
    wasteType: 'organico',
    wasteName: 'Residuos de Frutas y Cáscaras de Banano/Manzana',
    confidence: 98.2,
    inferenceTimeMs: 110,
    bagColor: 'Verde',
    colombianNormNote: 'Resoluciòn 2184/2019: Depositar directamente en Bolsa Verde para Compostaje.',
    recyclingSteps: [
      'Separar de plásticos o etiquetas adhesivas de las cáscaras.',
      'Depositar en el balde de compostaje o bolsa verde.',
    ],
    environmentalTips: [
      'El compostaje evita la emisión de gas metano CH4 tóxico en los rellenos sanitarios como Doña Juana o La Pradera.',
    ],
    estimatedWeightKg: 0.6,
    co2AvoidedKg: 0.48,
    waterSavedLiters: 3.0,
    energySavedKwh: 0.12,
    createdAt: '2026-07-23 08:45',
    status: 'verificado',
  },
  {
    id: 'cls-104',
    userId: 'u-2',
    userName: 'Javier Restrepo',
    imageUrl: 'https://images.unsplash.com/photo-1605559424843-9e4c228bf1c2?w=500',
    wasteType: 'metal',
    wasteName: 'Lata de Aluminio Bebida Energizante',
    confidence: 95.8,
    inferenceTimeMs: 130,
    bagColor: 'Blanco',
    colombianNormNote: 'Resoluciòn 2184/2019: Depositar en Bolsa Blanca.',
    recyclingSteps: ['Enjuagar interior', 'Aplastar verticalmente', 'Bolsa blanca'],
    environmentalTips: ['El aluminio se puede reciclar infinitas veces sin perder calidad.'],
    estimatedWeightKg: 0.15,
    co2AvoidedKg: 1.35,
    waterSavedLiters: 6.0,
    energySavedKwh: 2.1,
    createdAt: '2026-07-22 14:20',
    status: 'verificado',
  },
];

export const INITIAL_POINTS: CollectionPoint[] = [
  {
    id: 'pt-1',
    title: 'Punto de Reciclaje Edificio San Fernando',
    address: 'Cl. 10 # 43A - 25, El Poblado',
    neighborhood: 'El Poblado',
    coordinates: { lat: 6.2088, lng: -75.5678 },
    wasteTypesAvailable: ['pet', 'carton', 'papel', 'metal'],
    estimatedKg: 28.5,
    status: 'disponible',
    citizenName: 'Andrés Gómez',
    citizenContact: '312-555-0192',
    createdAt: '2026-07-25 09:00',
  },
  {
    id: 'pt-2',
    title: 'Conjunto Residencial Laureles Verde',
    address: 'Tv. 39B # 74 - 12',
    neighborhood: 'Laureles',
    coordinates: { lat: 6.2442, lng: -75.5891 },
    wasteTypesAvailable: ['vidrio', 'pet', 'carton'],
    estimatedKg: 42.0,
    status: 'disponible',
    citizenName: 'Carlos Mario Ruiz',
    citizenContact: '300-444-1234',
    createdAt: '2026-07-25 10:30',
  },
  {
    id: 'pt-3',
    title: 'Centro Comercial Oviedo - Punto Limpio',
    address: 'Av. El Poblado # 6Sur - 15',
    neighborhood: 'El Poblado',
    coordinates: { lat: 6.1985, lng: -75.5789 },
    wasteTypesAvailable: ['electronico', 'peligroso', 'metal'],
    estimatedKg: 15.0,
    status: 'en_camino',
    citizenName: 'Administración CC Oviedo',
    citizenContact: '304-888-9900',
    createdAt: '2026-07-25 08:15',
  },
  {
    id: 'pt-4',
    title: 'U. Residencial Belén Rosales',
    address: 'Cl. 32 # 70 - 45',
    neighborhood: 'Belén',
    coordinates: { lat: 6.2301, lng: -75.5920 },
    wasteTypesAvailable: ['organico', 'carton'],
    estimatedKg: 35.0,
    status: 'disponible',
    citizenName: 'Luz Marina Zapata',
    citizenContact: '315-999-7711',
    createdAt: '2026-07-25 11:00',
  },
];

export const INITIAL_RECORDS: CollectionRecord[] = [
  {
    id: 'rec-1',
    recyclerId: 'u-2',
    recyclerName: 'Javier Restrepo',
    pointId: 'pt-1',
    wasteType: 'carton',
    weightKg: 18.5,
    location: 'El Poblado - Cl. 10',
    notes: 'Cartón seco de embalaje en excelente estado.',
    createdAt: '2026-07-24 15:30',
  },
  {
    id: 'rec-2',
    recyclerId: 'u-2',
    recyclerName: 'Javier Restrepo',
    pointId: 'pt-1',
    wasteType: 'pet',
    weightKg: 10.0,
    location: 'El Poblado - Cl. 10',
    notes: 'Botellas PET aplastadas y limpias.',
    createdAt: '2026-07-24 15:45',
  },
];

export const INITIAL_INCIDENTS: IncidentReport[] = [
  {
    id: 'inc-1',
    reporterId: 'u-2',
    reporterName: 'Javier Restrepo',
    reporterRole: 'reciclador',
    title: 'Contenedor Blanco con residuos orgánicos en La 70',
    description: 'Encontré residuos de comida derramados dentro del contenedor de plástico blanco, contaminando el cartón seco.',
    category: 'contaminacion',
    severity: 'media',
    status: 'en_proceso',
    createdAt: '2026-07-24 11:20',
  },
  {
    id: 'inc-2',
    reporterId: 'u-1',
    reporterName: 'Andrés Gómez',
    reporterRole: 'ciudadano',
    title: 'Contenedor colapsado en Parque Lleras',
    description: 'El punto ecológico está saturado de bolsas de botellas de vidrio en la acera.',
    category: 'contenedor_lleno',
    severity: 'alta',
    status: 'abierto',
    createdAt: '2026-07-25 09:40',
  },
];

export const INITIAL_DATASET: DatasetSample[] = [
  {
    id: 'ds-001',
    filename: 'PET_bottle_clear_048.png',
    category: 'pet',
    split: 'train',
    dimensions: '224x224x3',
    confidenceThreshold: 0.95,
    verifiedByAdmin: true,
    uploadedAt: '2026-06-10',
  },
  {
    id: 'ds-002',
    filename: 'Cardboard_box_flat_102.png',
    category: 'carton',
    split: 'train',
    dimensions: '224x224x3',
    confidenceThreshold: 0.94,
    verifiedByAdmin: true,
    uploadedAt: '2026-06-11',
  },
  {
    id: 'ds-003',
    filename: 'Banana_peel_organic_012.png',
    category: 'organico',
    split: 'val',
    dimensions: '224x224x3',
    confidenceThreshold: 0.98,
    verifiedByAdmin: true,
    uploadedAt: '2026-06-12',
  },
  {
    id: 'ds-004',
    filename: 'Aluminum_can_soda_089.png',
    category: 'metal',
    split: 'test',
    dimensions: '224x224x3',
    confidenceThreshold: 0.96,
    verifiedByAdmin: true,
    uploadedAt: '2026-06-15',
  },
];

export const INITIAL_LOGS: SystemLog[] = [
  {
    id: 'log-101',
    timestamp: '2026-07-25 13:40:02',
    level: 'INFO',
    service: 'IA_ENGINE',
    message: 'Modelo EfficientNetV2-EcoVision infirió clase [pet] con 96.4% de confianza en 142ms.',
    ip: '192.168.1.45',
  },
  {
    id: 'log-102',
    timestamp: '2026-07-25 13:38:15',
    level: 'INFO',
    service: 'AUTH',
    message: 'Usuario JWT autenticado exitosamente: andres.gomez@ciudadano.org (Rol: ciudadano).',
    ip: '181.135.22.10',
  },
  {
    id: 'log-103',
    timestamp: '2026-07-25 13:30:00',
    level: 'INFO',
    service: 'DATABASE',
    message: 'Sincronización de réplica de lectura PostgreSQL finalizada sin latencia acumulada.',
    ip: '10.0.1.5',
  },
];

export const EDUCATIONAL_ARTICLES: EducationalArticle[] = [
  {
    id: 'art-1',
    title: 'Guía de la Código de Colores en Colombia (Resolución 2184 de 2019)',
    summary: 'Aprende a separar correctamente en Bolsa Blanca, Verde y Negra para felicitar el trabajo de los recicladores de oficio.',
    content: `En Colombia, la Resolución 2184 de 2019 unificó el código de colores para la separación de residuos en la fuente en todo el territorio nacional:

1. **Bolsa Blanca**: Residuos aprovechables secos y limpios. Incluye plástico PET, botellas, bolsas limpias, vidrio entero, cartón corrugado, papel bond y latas de aluminio.
2. **Bolsa Verde**: Residuos orgánicos biodegradables. Incluye cáscaras de frutas, verduras, restos de hortalizas, restos de podas de jardín y hojarasca.
3. **Bolsa Negra**: Residuos no aprovechables. Incluye servilletas usadas, papel higiénico, cartón sucio de grasa/queso, colillas y empaques metalizados de frituras.

Separar en la fuente dignifica el trabajo de más de 60,000 recicladores de oficio en Colombia y aumenta la tasa de aprovechamiento nacional del 14% hacia la meta del 30%.`,
    category: 'Normativa Colombiana',
    readTimeMinutes: 4,
    author: 'Dra. Elena Monsalve',
    publishedAt: '2026-07-10',
    imageUrl: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?w=600',
  },
  {
    id: 'art-2',
    title: 'El Viaje del PET: Cómo tu botella de agua se convierte en fibra textil',
    summary: 'Descubre el ciclo de economía circular que transforma botellas de plástico transparente en chaquetas, telas y nuevos envases.',
    content: `Cuando reciclas una botella PET en la Bolsa Blanca, inicia un proceso industrial fascinante:

1. **Recolección y Clasificación**: Los recicladores de oficio acopian las botellas y las separan por color (transparente vs verde/azul).
2. **Compactación en Pacas**: Las botellas son prensadas hidráulicamente en bloques de 100 kg.
3. **Trituración y Molido**: Las botellas son trituradas en finas hojuelas llamadas "Flakes".
4. **Lavado Químico**: Se retiran etiquetas, pegantes y tapas de polipropileno por flotación.
5. **Fundición y Extrusión**: Los flakes se funden a 260°C para crear hilo de poliéster reciclado (rPET) con el que se fabrican camisas, cobijas y nuevas botellas.`,
    category: 'Economía Circular',
    readTimeMinutes: 6,
    author: 'Ing. Mateo Bermúdez',
    publishedAt: '2026-07-15',
    imageUrl: 'https://images.unsplash.com/photo-1611284446314-60a58ac0deb9?w=600',
  },
];
